[package]
name = "help_output_validation"
version = "0.1.0"
authors = ["Hazel OHearn <gygaxis@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
